services:
  productdb:
    container_name: productdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ProductDB
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
     container_name: pgadmin
     environment:
       - PGADMIN_DEFAULT_EMAIL=m.pourghorban2004@gmail.com
       - PGADMIN_DEFAULT_PASSWORD=123456
     restart: always
     ports:
       - "5070:80"
     volumes:
       - pgadmin_data:/root/.pgadmin
 
  products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "10000:80"
    depends_on:
      - productdb
